(() => {
  "use strict";
  const body=document.getElementById("modalBody"),overlay=document.getElementById("modalOverlay"),modalCard=document.getElementById("modalCard");
  if(!body||!overlay)return;
  const W=960,H=600,MAX=1650,PHP=5,MINY=215,R=9,RESUME_KEY="red_school_roger_checkpoint_resume_v2";
  let session=null,scheduled=false,bridge=false;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),d2=(a,b,c,d)=>(a-c)**2+(b-d)**2;

  function legacyOpen(){if(bridge||session||!overlay.classList.contains("show")||body.querySelector(".overload-boss-v2"))return false;const h=body.querySelector(".boss-panel h2")?.textContent||"";return /超負荷/.test(h)&&!!body.querySelector("[data-side]")}
  function consumeResume(){let x=window.__bossResumeIntent;try{x=x||JSON.parse(sessionStorage.getItem(RESUME_KEY)||"null")}catch(_){};if(x?.boss!=="overload")return 1;const p=clamp(Number(x.phase)||1,1,3);sessionStorage.removeItem(RESUME_KEY);delete window.__bossResumeIntent;return p}
  function stop(){const s=session;if(!s)return;s.dead=true;if(s.raf)cancelAnimationFrame(s.raf);document.removeEventListener("keydown",s.kd,true);document.removeEventListener("keyup",s.ku,true);document.removeEventListener("visibilitychange",s.vis);session=null;modalCard?.classList.remove("overload-boss-card")}
  function takeLegacy(){const f=document.createDocumentFragment();while(body.firstChild)f.appendChild(body.firstChild);return f}

  function takeover(){
    if(!legacyOpen())return;
    const legacy=takeLegacy(),phase=consumeResume(),hp=phase===1?MAX:phase===2?1070:490;
    modalCard?.classList.add("overload-boss-card");
    body.innerHTML=`<div class="overload-boss-v2 overload-boss-v3" data-phase="${phase}" data-playing="0">
      <div class="ob2-head"><div><div class="eyebrow">BOSS · BULLET HELL V3</div><h2>大肥哥超負荷</h2></div><div class="ob2-phase-label"><span>PHASE</span><b data-phase-label>${phase} / 3</b></div></div>
      <div class="ob2-bossbar"><div class="ob2-bossbar-top"><span>OVERLOAD</span><b data-boss-hp>${hp}</b></div><div class="ob2-bar"><i data-boss-bar></i></div></div>
      <div class="ob2-arena-wrap"><div class="ob2-boss-visual" aria-hidden="true"><svg viewBox="0 0 300 380"><use href="assets/art.svg#portrait-overload" width="300" height="380"></use></svg></div><canvas class="ob2-canvas" width="${W}" height="${H}"></canvas><div class="ob2-attack-banner" data-attack>準備戰鬥</div><div class="ob2-phase-banner" data-phase-banner></div><div class="ob2-countdown" data-countdown><div class="ob2-ready"><b>${phase>1?`CHECKPOINT · PHASE ${phase}`:"超負荷開始過載"}</b><span>滑鼠／觸控拖曳移動 · 方向鍵可輔助 · Shift 精密移動</span><button type="button" class="primary" data-start>${phase>1?"從此階段繼續":"開始戰鬥"}</button></div></div></div>
      <div class="ob2-status"><div class="ob2-player-hp"><span>羅正男</span><b data-hearts>♥ ♥ ♥ ♥ ♥</b></div><div class="ob2-graze"><div><span>反擊槽</span><b data-graze-label>0%</b></div><div class="ob2-bar"><i data-graze-bar></i></div></div><div class="ob2-score"><span>SCORE</span><b data-score>000000</b></div><div class="ob2-graze-count"><span>GRAZE</span><b data-graze-count>0</b></div><button type="button" class="boss-touch-special" data-counter>反擊槽未滿</button></div>
    </div>`;
    const root=body.querySelector(".overload-boss-v2"),canvas=root.querySelector("canvas"),ctx=canvas.getContext("2d");
    const img=new Image();img.src="assets/characters/luozhengnan.webp";
    const s={root,canvas,ctx,legacy,img,dead:false,finished:false,started:false,paused:false,raf:0,last:performance.now(),elapsed:0,phase,phasePause:phase>1?1.2:0,bossHp:hp,player:{x:W/2,y:H-80,tx:W/2,ty:H-80,hp:PHP,inv:phase>1?1.8:0},keys:{},bullets:[],shots:[],lasers:[],particles:[],pattern:null,pi:phase*2,shot:0,graze:phase>1?25:0,gc:0,score:0,shake:0,flash:0,kd:null,ku:null,vis:null};
    session=s;bind(s);hud(s);draw(s);root.querySelector("[data-start]").onclick=()=>countdown(s);window.GameAudio?.setMode?.("boss",{force:true,restart:true});
  }

  function bind(s){
    const pos=e=>{const r=s.canvas.getBoundingClientRect();s.player.tx=clamp((e.clientX-r.left)*W/r.width,24,W-24);s.player.ty=clamp((e.clientY-r.top)*H/r.height,MINY,H-28)};
    s.canvas.addEventListener("pointerdown",e=>{e.preventDefault();s.canvas.setPointerCapture?.(e.pointerId);pos(e)});s.canvas.addEventListener("pointermove",e=>{if(e.pointerType==="mouse"||e.buttons)pos(e)});
    s.root.querySelector("[data-counter]").onclick=()=>counter(s);s.canvas.addEventListener("contextmenu",e=>{e.preventDefault();counter(s)});
    s.kd=e=>{if(session!==s||s.finished)return;const k=e.key.toLowerCase();if(["arrowleft","arrowright","arrowup","arrowdown","a","d","w","s","shift"," "].includes(k))e.preventDefault();s.keys[k]=true;if(k===" "&&!e.repeat)counter(s)};s.ku=e=>{s.keys[e.key.toLowerCase()]=false};
    document.addEventListener("keydown",s.kd,true);document.addEventListener("keyup",s.ku,true);s.vis=()=>{s.paused=document.hidden;s.last=performance.now()};document.addEventListener("visibilitychange",s.vis);
  }
  function countdown(s){if(s.started)return;const box=s.root.querySelector("[data-countdown]"),seq=["3","2","1","FIGHT"];seq.forEach((t,i)=>setTimeout(()=>{if(session!==s)return;box.innerHTML=`<strong>${t}</strong>`;if(i<3)window.GameAudio?.playConfirm?.();if(t==="FIGHT")setTimeout(()=>start(s),400)},i*650))}
  function start(s){s.started=true;s.root.dataset.playing="1";s.root.querySelector("[data-countdown]")?.classList.add("hide");choose(s,true);s.last=performance.now();s.raf=requestAnimationFrame(n=>frame(s,n))}
  function frame(s,n){if(session!==s||s.dead||!document.contains(s.root)){stop();return}if(s.paused){s.raf=requestAnimationFrame(x=>frame(s,x));return}const dt=clamp((n-s.last)/1000,0,.034);s.last=n;s.elapsed+=dt;s.player.inv=Math.max(0,s.player.inv-dt);s.shake=Math.max(0,s.shake-dt*10);move(s,dt);shoot(s,dt);if(s.phasePause>0)s.phasePause-=dt;else pattern(s,dt);shots(s,dt);bullets(s,dt);lasers(s,dt);particles(s,dt);phaseCheck(s);hud(s);draw(s);if(s.player.hp<=0)return lose(s);if(s.bossHp<=0)return win(s);s.raf=requestAnimationFrame(x=>frame(s,x))}
  function move(s,dt){let dx=0,dy=0,k=s.keys;if(k.arrowleft||k.a)dx--;if(k.arrowright||k.d)dx++;if(k.arrowup||k.w)dy--;if(k.arrowdown||k.s)dy++;if(dx||dy){const m=Math.hypot(dx,dy)||1,sp=(k.shift?155:335);s.player.x+=dx/m*sp*dt;s.player.y+=dy/m*sp*dt;s.player.tx=s.player.x;s.player.ty=s.player.y}else{const a=1-Math.exp(-dt*11);s.player.x+=(s.player.tx-s.player.x)*a;s.player.y+=(s.player.ty-s.player.y)*a}s.player.x=clamp(s.player.x,24,W-24);s.player.y=clamp(s.player.y,MINY,H-28)}
  function shoot(s,dt){s.shot-=dt;if(s.phasePause>0)return;while(s.shot<=0){s.shot+=.095;s.shots.push({x:s.player.x-6,y:s.player.y-22,vy:-610},{x:s.player.x+6,y:s.player.y-22,vy:-610})}}
  function shots(s,dt){for(let i=s.shots.length-1;i>=0;i--){const q=s.shots[i];q.y+=q.vy*dt;if(q.y<150&&Math.abs(q.x-W/2)<115){s.bossHp=Math.max(0,s.bossHp-3.2);s.score+=10;s.shots.splice(i,1)}else if(q.y<-20)s.shots.splice(i,1)}}
  function choose(s,first=false){const pools={1:["fan","aim","rain"],2:["ring","wall","aim","laser"],3:["spiral","laser","wall","ring","frenzy"]},a=pools[s.phase],type=a[s.pi++%a.length];s.pattern={type,t:0,next:0,spin:rand(0,6.28),wave:0,dur:s.phase===3?4.1:4.6};attackText(s,({fan:"嘴砲扇形",aim:"鎖定連射",rain:"聊天室暴雨",ring:"過載環爆",wall:"左右封鎖牆",laser:"紅線封鎖",spiral:"失控螺旋",frenzy:"全頻過載"})[type])}
  function spawn(s,x,y,vx,vy,r=6,turn=0){s.bullets.push({x,y,vx,vy,r,turn,g:false,age:0})}
  function pattern(s,dt){let p=s.pattern;if(!p)return choose(s,true);p.t+=dt;p.next-=dt;const hard=s.phase===3?1.2:s.phase===2?1.08:1;if(p.next<=0){if(p.type==="fan"){p.next=.55/hard;for(let i=-4;i<=4;i++){const a=Math.PI/2+i*.11;spawn(s,W/2,115,Math.cos(a)*180*hard,Math.sin(a)*180*hard)}}else if(p.type==="aim"){p.next=.68/hard;const a=Math.atan2(s.player.y-112,s.player.x-W/2);for(const o of[-.16,-.08,0,.08,.16])spawn(s,W/2,112,Math.cos(a+o)*240*hard,Math.sin(a+o)*240*hard,6,s.phase>1&&o===0?.38:0)}else if(p.type==="rain"){p.next=.13;spawn(s,rand(25,W-25),-10,rand(-35,35),rand(180,245)*hard,5)}else if(p.type==="ring"){p.next=.78/hard;p.spin+=.25;const n=s.phase===3?24:18;for(let i=0;i<n;i++){const a=p.spin+i*6.283/n;spawn(s,W/2,118,Math.cos(a)*155*hard,Math.sin(a)*155*hard)}}else if(p.type==="wall"){p.next=.63/hard;const left=(p.wave++%2)===0,gap=Math.floor(rand(1,5));for(let r=0;r<6;r++)if(r!==gap&&r!==gap-1)spawn(s,left?-20:W+20,MINY+r*66,left?215*hard:-215*hard,0,8)}else if(p.type==="laser"){p.next=1.25;s.lasers.push({x:clamp(s.player.x+rand(-120,120),55,W-55),w:s.phase===3?56:46,t:0,tele:.7,active:.6,hit:false})}else if(p.type==="spiral"){p.next=.07;p.spin+=.24;spawn(s,W/2,118,Math.cos(p.spin)*180,Math.sin(p.spin)*180,5)}else{p.next=.2;p.spin+=.38;for(const o of[-.34,0,.34])spawn(s,W/2,118,Math.cos(p.spin+o)*210,Math.sin(p.spin+o)*210,6);if(p.wave++%10===0)s.lasers.push({x:rand(70,W-70),w:48,t:0,tele:.6,active:.5,hit:false})}}if(p.t>p.dur)choose(s)}
  function bullets(s,dt){const P=s.player;for(let i=s.bullets.length-1;i>=0;i--){const b=s.bullets[i];b.age+=dt;if(b.turn){const cur=Math.atan2(b.vy,b.vx),tar=Math.atan2(P.y-b.y,P.x-b.x),df=((tar-cur+Math.PI*3)%(Math.PI*2))-Math.PI,a=cur+clamp(df,-b.turn*dt,b.turn*dt),sp=Math.hypot(b.vx,b.vy);b.vx=Math.cos(a)*sp;b.vy=Math.sin(a)*sp}b.x+=b.vx*dt;b.y+=b.vy*dt;const hr=R+b.r*.72,dd=d2(b.x,b.y,P.x,P.y);if(!b.g&&dd<(hr+24)**2&&dd>hr**2){b.g=true;s.gc++;s.graze=clamp(s.graze+3,0,100);s.score+=35}if(P.inv<=0&&dd<hr**2){damage(s);s.bullets.splice(i,1);continue}if(b.x<-70||b.x>W+70||b.y<-80||b.y>H+80||b.age>13)s.bullets.splice(i,1)}}
  function lasers(s,dt){for(let i=s.lasers.length-1;i>=0;i--){const l=s.lasers[i];l.t+=dt;if(l.t>=l.tele&&l.t<l.tele+l.active&&!l.hit&&s.player.inv<=0&&Math.abs(s.player.x-l.x)<l.w/2+R){l.hit=true;damage(s)}if(l.t>l.tele+l.active+.2)s.lasers.splice(i,1)}}
  function damage(s){s.player.hp--;s.player.inv=1.05;s.graze=Math.max(0,s.graze-20);s.shake=7;s.bullets=s.bullets.filter(b=>d2(b.x,b.y,s.player.x,s.player.y)>95**2);navigator.vibrate?.(50)}
  function counter(s){if(!s.started||s.finished||s.graze<100)return;s.graze=0;s.bossHp=Math.max(0,s.bossHp-135);s.score+=1500;s.player.inv=Math.max(1.1,s.player.inv);s.bullets.length=0;s.lasers.length=0;attackText(s,"聊天室反擊！");window.GameAudio?.playConfirm?.()}
  function particles(){}
  function phaseCheck(s){const next=s.bossHp<=495?3:s.bossHp<=1072?2:1;if(next<=s.phase)return;s.phase=next;s.root.dataset.phase=String(next);s.root.querySelector("[data-phase-label]").textContent=`${next} / 3`;s.bullets.length=0;s.lasers.length=0;s.pattern=null;s.phasePause=1.2;s.player.inv=1.4;s.graze=clamp(s.graze+25,0,100);banner(s,next===2?"PHASE 2 · 聊天室失控":"FINAL PHASE · 全頻過載")}
  function hud(s){const hp=Math.max(0,s.bossHp);s.root.querySelector("[data-boss-hp]").textContent=Math.ceil(hp);s.root.querySelector("[data-boss-bar]").style.width=`${hp/MAX*100}%`;s.root.querySelector("[data-hearts]").textContent=Array.from({length:PHP},(_,i)=>i<s.player.hp?"♥":"♡").join(" ");s.root.querySelector("[data-graze-label]").textContent=`${Math.floor(s.graze)}%${s.graze>=100?" READY":""}`;s.root.querySelector("[data-graze-bar]").style.width=`${s.graze}%`;s.root.querySelector("[data-score]").textContent=String(Math.floor(s.score)).padStart(6,"0");s.root.querySelector("[data-graze-count]").textContent=s.gc;const b=s.root.querySelector("[data-counter]");b.disabled=s.graze<100;b.textContent=s.graze>=100?"反擊 / 清彈":"反擊槽未滿"}
  function attackText(s,t){const e=s.root.querySelector("[data-attack]");if(e)e.textContent=t}function banner(s,t){const e=s.root.querySelector("[data-phase-banner]");if(!e)return;e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1000)}
  function draw(s){const c=s.ctx;c.clearRect(0,0,W,H);c.save();if(s.shake)c.translate(rand(-s.shake,s.shake),rand(-s.shake,s.shake));c.strokeStyle="rgba(140,50,65,.22)";for(let x=0;x<W;x+=80){c.beginPath();c.moveTo(x,MINY);c.lineTo(W/2+(x-W/2)*1.2,H);c.stroke()}for(const l of s.lasers){if(l.t<l.tele){c.fillStyle="rgba(255,80,95,.45)";c.fillRect(l.x-2,0,4,H)}else{c.fillStyle="rgba(255,40,65,.8)";c.fillRect(l.x-l.w/2,0,l.w,H);c.fillStyle="#fff1d0";c.fillRect(l.x-3,0,6,H)}}c.fillStyle="#ffe998";for(const q of s.shots)c.fillRect(q.x-2,q.y-8,4,14);for(const b of s.bullets){c.fillStyle="#f14860";c.shadowBlur=7;c.shadowColor="#f14860";c.beginPath();c.arc(b.x,b.y,b.r,0,6.283);c.fill()}c.shadowBlur=0;drawPlayer(s,c);c.restore()}
  function drawPlayer(s,c){const p=s.player;c.save();if(p.inv>0&&Math.floor(p.inv*12)%2===0)c.globalAlpha=.35;c.translate(p.x,p.y);if(s.img.complete&&s.img.naturalWidth)c.drawImage(s.img,-27,-55,54,72);else{c.fillStyle="#fff";c.beginPath();c.arc(0,-8,14,0,6.28);c.fill()}c.fillStyle="#fff59d";c.beginPath();c.arc(0,0,4,0,6.28);c.fill();c.restore()}
  function win(s){if(s.finished)return;s.finished=true;banner(s,"OVERLOAD BREAK");setTimeout(()=>bridgeWin(s),800)}function lose(s){if(s.finished)return;s.finished=true;banner(s,"OVERLOAD");setTimeout(()=>bridgeLose(s),700)}
  function restore(s){modalCard?.classList.remove("overload-boss-card");body.innerHTML="";body.appendChild(s.legacy)}const nf=()=>new Promise(r=>requestAnimationFrame(r));
  async function bridgeWin(s){bridge=true;stop();restore(s);await nf();for(let g=0;g<60;g++){if(!overlay.classList.contains("show")||!body.querySelector(".boss-panel"))break;const log=body.querySelector(".boss-log")?.textContent||"",m=log.match(/第\s*(\d+)\s*區/),danger=m?+m[1]-1:-1,lanes=[...body.querySelectorAll("[data-lane]")],sides=[...body.querySelectorAll("[data-side]")],side=/左/.test(log)?"L":"R";if(lanes.length){lanes.find(b=>+b.dataset.lane!==danger)?.click();await nf()}body.querySelector(`[data-side="${side}"]`)?.click();await nf()}setTimeout(()=>{bridge=false;schedule();window.GameAudio?.refreshBgmMode?.()},150)}
  async function bridgeLose(s){bridge=true;stop();restore(s);await nf();for(let g=0;g<8;g++){if(!body.querySelector(".boss-panel"))break;const log=body.querySelector(".boss-log")?.textContent||"",correct=/左/.test(log)?"L":"R",wrong=correct==="L"?"R":"L";body.querySelector(`[data-side="${wrong}"]`)?.click();await nf()}setTimeout(()=>{bridge=false;schedule()},150)}
  function scan(){scheduled=false;if(session&&!document.contains(session.root))stop();if(!bridge&&!session&&legacyOpen())takeover()}function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(scan)}new MutationObserver(schedule).observe(body,{childList:true,subtree:true});new MutationObserver(schedule).observe(overlay,{attributes:true,attributeFilter:["class"]});schedule();
})();
