(() => {
  "use strict";
  const body=document.getElementById("modalBody"),overlay=document.getElementById("modalOverlay"),modalCard=document.getElementById("modalCard");
  if(!body||!overlay||!modalCard)return;
  const W=960,H=600,MAX=3200,PHP=5,R=8,RESUME_KEY="red_school_roger_checkpoint_resume_v2";
  const QUESTIONS=[
    {q:"二年三班真正異常的是？",a:["黑板","第 32 張桌子","窗簾"],correct:"第 32 張桌子",note:"名冊只有 31 人，但教室裡多出第 32 張桌子。"},
    {q:"外牆與二樓走廊對不上的數量是？",a:["第 6 扇窗","第 8 扇窗","第 9 扇窗"],correct:"第 8 扇窗",note:"外牆只有 7 扇，二樓內側卻出現第 8 扇。"},
    {q:"超負荷真正沒辦法放學的原因是？",a:["想繼續打架","三件沒完成的心願","想佔領學校"],correct:"三件沒完成的心願",note:"便當袋、遊戲卡、畢業照是三個心願碎片。"},
    {q:"教職員室點名簿最後一列寫的是？",a:["缺席","還沒放學","紅色學校"],correct:"還沒放學",note:"最後一列不是姓名，而是『還沒放學』。"}
  ];
  const BAN=[
    {note:"名冊 31 人，異常的是第 32 張桌子。",labels:["31","32","33"],c:1},
    {note:"外牆 7 扇，真正多出來的是第 8 扇窗。",labels:["7","8","9"],c:1},
    {note:"地下機房真正通往深處的是紅色電纜。",labels:["BLACK","RED","BLUE"],c:1},
    {note:"逆拍樂譜每第 4 小節故意少一拍。",labels:["3rd","4th","5th"],c:1}
  ];
  let session=null,scheduled=false,bridge=false;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),d2=(a,b,c,d)=>(a-c)**2+(b-d)**2,shuffle=a=>{a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};

  function legacyOpen(){if(bridge||session||!overlay.classList.contains("show")||body.querySelector(".pyramid-boss-v2"))return false;return /金字塔紹安/.test(body.querySelector(".boss-panel h2")?.textContent||"")&&!!body.querySelector("[data-q]")}
  function consumeResume(){let x=window.__bossResumeIntent;try{x=x||JSON.parse(sessionStorage.getItem(RESUME_KEY)||"null")}catch(_){};if(x?.boss!=="pyramid")return 1;const p=clamp(Number(x.phase)||1,1,4);sessionStorage.removeItem(RESUME_KEY);delete window.__bossResumeIntent;return p}
  function takeLegacy(){const f=document.createDocumentFragment();while(body.firstChild)f.appendChild(body.firstChild);return f}
  function stop(){const s=session;if(!s)return;s.dead=true;if(s.raf)cancelAnimationFrame(s.raf);document.removeEventListener("keydown",s.kd,true);document.removeEventListener("keyup",s.ku,true);session=null;modalCard.classList.remove("pyramid-boss-modal")}

  function takeover(){
    if(!legacyOpen())return;const legacy=takeLegacy(),phase=consumeResume(),hp=phase===1?MAX:phase===2?2300:phase===3?1500:750;
    body.innerHTML=`<div class="pyramid-boss-v2 pyramid-boss-v3" data-phase="${phase}"><div class="pyr2-head"><div><div class="eyebrow">HIDDEN FINAL BOSS · TRUTH COLLAPSE V3</div><h2>金字塔紹安</h2></div><div class="pyr2-phase" data-phase-label></div></div><div class="pyr2-bars"><div><span>SHAOAN</span><i class="pyr2-bossbar"><b data-bossbar></b></i></div><div><span>ROGER</span><i class="pyr2-playerbar"><b data-playerbar></b></i></div><div class="pyr2-resolve"><span>CASE BREAK</span><i><b data-resolve></b></i></div></div><div class="pyr2-stage-wrap"><canvas class="pyr2-canvas" width="${W}" height="${H}"></canvas><div class="pyr3-countdown" data-countdown><div><b>${phase>1?`CHECKPOINT · PHASE ${phase}`:"MEMORY JUDGEMENT"}</b><span>答案位置每題會重排，而且答案區會移動；閃彈幕的同時完成審判。</span><button class="primary" type="button" data-start>${phase>1?"從此階段繼續":"開始審判"}</button></div></div><button type="button" class="pyr2-confirm boss-touch-special" data-special>確認答案</button></div><div class="pyr2-foot"><span>滑鼠／觸控拖曳移動 · 方向鍵可輔助</span><span>手機可直接按右下特殊技 · Shift 精密移動</span></div></div>`;
    modalCard.classList.add("pyramid-boss-modal");const root=body.querySelector(".pyramid-boss-v2"),canvas=root.querySelector("canvas"),ctx=canvas.getContext("2d");
    const s={root,canvas,ctx,legacy,dead:false,finished:false,started:false,raf:0,last:performance.now(),elapsed:0,phase,transition:phase>1?1.5:0,boss:{x:480,y:92,hp,max:MAX},player:{x:480,y:525,tx:480,ty:525,hp:PHP,inv:phase>1?2:0},keys:{},bullets:[],shots:[],lasers:[],particles:[],attack:0,pattern:0,shot:0,resolve:phase>1?30:0,graze:0,score:0,q:0,qOrder:shuffle(QUESTIONS[0].a),qLock:.8,feedback:"",feedbackT:0,roomMode:0,roomT:0,ban:null,banNext:2.8,banIndex:0};
    session=s;bind(s);dom(s);draw(s);root.querySelector("[data-start]").onclick=()=>countdown(s);window.GameAudio?.setMode?.("boss",{force:true,restart:true});
  }
  function bind(s){const pos=e=>{const r=s.canvas.getBoundingClientRect();s.player.tx=clamp((e.clientX-r.left)*W/r.width,28,W-28);s.player.ty=clamp((e.clientY-r.top)*H/r.height,190,H-28)};s.canvas.addEventListener("pointerdown",e=>{e.preventDefault();s.canvas.setPointerCapture?.(e.pointerId);pos(e)});s.canvas.addEventListener("pointermove",e=>{if(e.pointerType==="mouse"||e.buttons)pos(e)});s.root.querySelector("[data-special]").onclick=()=>special(s);s.kd=e=>{if(session!==s)return;const k=e.key.toLowerCase();if(["arrowleft","arrowright","arrowup","arrowdown","w","a","s","d","shift"," "].includes(k))e.preventDefault();s.keys[k]=true;if(k===" "&&!e.repeat)special(s)};s.ku=e=>s.keys[e.key.toLowerCase()]=false;document.addEventListener("keydown",s.kd,true);document.addEventListener("keyup",s.ku,true)}
  function countdown(s){if(s.started)return;const b=s.root.querySelector("[data-countdown]"),seq=["3","2","1","JUDGE"];seq.forEach((t,i)=>setTimeout(()=>{if(session!==s)return;b.innerHTML=`<strong>${t}</strong>`;if(i<3)window.GameAudio?.playConfirm?.();if(t==="JUDGE")setTimeout(()=>start(s),380)},i*650))}
  function start(s){s.started=true;s.root.querySelector("[data-countdown]")?.classList.add("hide");s.last=performance.now();s.raf=requestAnimationFrame(n=>frame(s,n))}
  function frame(s,n){if(session!==s||s.dead||!document.contains(s.root)){stop();return}const dt=clamp((n-s.last)/1000,0,.04);s.last=n;s.elapsed+=dt;if(s.feedbackT>0)s.feedbackT-=dt;if(s.qLock>0)s.qLock-=dt;if(s.player.inv>0)s.player.inv-=dt;move(s,dt);if(s.transition>0)s.transition-=dt;else{shoot(s,dt);attacks(s,dt);bullets(s,dt);lasers(s,dt)}shots(s,dt);phaseCheck(s);dom(s);draw(s);if(s.player.hp<=0)return lose(s);if(s.boss.hp<=0)return win(s);s.raf=requestAnimationFrame(x=>frame(s,x))}
  function move(s,dt){let dx=0,dy=0,k=s.keys;if(k.arrowleft||k.a)dx--;if(k.arrowright||k.d)dx++;if(k.arrowup||k.w)dy--;if(k.arrowdown||k.s)dy++;if(dx||dy){const m=Math.hypot(dx,dy)||1,sp=k.shift?170:330;s.player.x+=dx/m*sp*dt;s.player.y+=dy/m*sp*dt;s.player.tx=s.player.x;s.player.ty=s.player.y}else{const a=1-Math.exp(-dt*10);s.player.x+=(s.player.tx-s.player.x)*a;s.player.y+=(s.player.ty-s.player.y)*a}s.player.x=clamp(s.player.x,28,W-28);s.player.y=clamp(s.player.y,190,H-28)}
  function shoot(s,dt){if(s.phase===1)return;s.shot-=dt;while(s.shot<=0){s.shot+=.105;s.shots.push({x:s.player.x-5,y:s.player.y-10,vy:-610},{x:s.player.x+5,y:s.player.y-10,vy:-610})}}
  function shots(s,dt){for(let i=s.shots.length-1;i>=0;i--){let a=s.shots[i];a.y+=a.vy*dt;if(a.y<-15){s.shots.splice(i,1);continue}if(s.phase>1&&d2(a.x,a.y,s.boss.x,s.boss.y)<46**2){s.boss.hp=clamp(s.boss.hp-5,0,MAX);s.score+=10;s.shots.splice(i,1)}}}
  function currentQ(s){const q=QUESTIONS[s.q];return q?{...q,order:s.qOrder,correctIndex:s.qOrder.indexOf(q.correct)}:null}
  function answerZones(s){const t=s.elapsed,q=s.q;return[0,1,2].map((_,i)=>({x:[175,480,785][i]+Math.sin(t*1.15+i*2+q)*24,y:478+Math.cos(t*.92+i*1.7+q)*20,r:70}))}
  function special(s){if(!s.started||s.transition>0)return;if(s.phase===1)return confirm(s);if(s.resolve<100){s.feedback="CASE BREAK 尚未充滿";s.feedbackT=.7;return}s.resolve=0;s.bullets.length=0;s.lasers=s.lasers.filter(l=>l.tele>0);s.player.inv=Math.max(s.player.inv,1.1);s.boss.hp=clamp(s.boss.hp-140,0,MAX);s.feedback="CASE BREAK · 真相清場";s.feedbackT=1;window.GameAudio?.playConfirm?.()}
  function confirm(s){if(s.qLock>0||s.q>=QUESTIONS.length)return;const z=answerZones(s);let pick=-1;z.forEach((a,i)=>{if(d2(s.player.x,s.player.y,a.x,a.y)<a.r*a.r)pick=i});if(pick<0){s.feedback="先進入一個答案區";s.feedbackT=.8;return}const q=currentQ(s);if(pick===q.correctIndex){s.boss.hp=clamp(s.boss.hp-225,0,MAX);s.resolve=clamp(s.resolve+20,0,100);s.q++;s.bullets.length=0;s.lasers.length=0;s.feedback="TRUTH ACCEPTED";s.feedbackT=1;s.qLock=.9;if(s.q>=QUESTIONS.length){s.boss.hp=Math.min(s.boss.hp,2300);enter(s,2,"TRIANGLE HELL")}else s.qOrder=shuffle(QUESTIONS[s.q].a)}else{hit(s,true);s.feedback="FALSE MEMORY";s.feedbackT=1;s.qLock=.65;ring(s,s.boss.x,s.boss.y,16,155,"#ff315c",false)}}
  function enter(s,p,label){s.phase=p;s.root.dataset.phase=String(p);s.transition=2;s.bullets.length=0;s.lasers.length=0;s.shots.length=0;s.player.inv=2;s.attack=.7;s.feedback=`PHASE ${p} · ${label}`;s.feedbackT=1.8;if(p===3){s.roomMode=0;s.roomT=0}if(p===4){s.banNext=2.3;s.root.classList.add("ban-mode")}}
  function attacks(s,dt){s.attack-=dt;if(s.phase===1){if(s.attack<=0){s.attack=.58;memory(s)}return}if(s.phase===2){if(s.attack<=0){s.attack=.53;triangle(s)}return}if(s.phase===3){s.roomT+=dt;if(s.roomT>4.2){s.roomMode=(s.roomMode+1)%4;s.roomT=0;s.bullets.length=0;s.feedback=`ROOM SHIFT · ${["二年三班","圖書館","音樂教室","地下機房"][s.roomMode]}`;s.feedbackT=1}if(s.attack<=0)room(s);return}if(s.phase===4){s.banNext-=dt;if(s.ban&&!s.ban.done){s.ban.time-=dt;if(s.ban.time<=0)resolveBan(s)}else if(s.banNext<=0)startBan(s);if(s.attack<=0){s.attack=.31;banAttack(s)}}}
  function spawn(s,x,y,vx,vy,r=7,color="#ff315c",fake=false,extra={}){s.bullets.push({x,y,vx,vy,r,color,fake,g:false,age:0,...extra})}function fan(s,x,y,tx,ty,n,spread,sp,color,fake=false){const a=Math.atan2(ty-y,tx-x),m=(n-1)/2;for(let i=0;i<n;i++){const z=a+(i-m)*spread;spawn(s,x,y,Math.cos(z)*sp,Math.sin(z)*sp,7,color,fake)}}function ring(s,x,y,n,sp,color,fake=false){const off=s.elapsed*.65;for(let i=0;i<n;i++){const a=off+i*6.283/n;spawn(s,x,y,Math.cos(a)*sp,Math.sin(a)*sp,7,color,fake)}}
  function memory(s){if(Math.random()<.55){const x=rand(80,W-80);for(let i=-2;i<=2;i++)spawn(s,x,105,i*42,185+Math.abs(i)*8,7,"#985cff",false,{wave:rand(1.5,3)})}else fan(s,Math.random()<.5?90:870,120,s.player.x,s.player.y,6,.15,205,"#ff5575")}
  function triangle(s){const c=[[95,118],[865,118],[480,65]],k=s.pattern++%6;if(k===0)c.forEach((a,n)=>fan(s,a[0],a[1],s.player.x,s.player.y,5,.13,215+n*7,n===2?"#ffd052":"#ff315c"));else if(k===1)ring(s,480,92,22,165,"#9d69ff");else if(k===2){const a=c[s.pattern%3];for(let i=0;i<9;i++){const z=i*6.283/9+s.elapsed;spawn(s,a[0],a[1],Math.cos(z)*195,Math.sin(z)*195,7,"#ff6b90",false,{curve:i%2?.55:-.55})}}else if(k===3){for(let x=70;x<W;x+=88)spawn(s,x,-10,rand(-20,20),195+rand(0,50),6,"#70e4ff")}else if(k===4)laser(s,rand(160,800),0,rand(160,800),H,1,.42,"#ff284e",false);else c.forEach(a=>ring(s,a[0],a[1],10,185,"#e754ff"))}
  function room(s){const m=s.roomMode;if(m===0){s.attack=.56;const y=rand(245,520),from=Math.random()<.5?-30:W+30,v=from<0?230:-230;for(let j=0;j<3;j++)spawn(s,from,y+j*28,v,0,12,"#b7795a",false,{shape:"desk"})}else if(m===1){s.attack=.21;spawn(s,rand(45,W-45),-15,rand(-60,60),175+rand(0,70),7,"#e8ddc5",false,{shape:"paper",wave:rand(2,4)})}else if(m===2){s.attack=.36;const lane=Math.floor(rand(0,6)),x=120+lane*144;spawn(s,x,-12,0,235,8,"#ff6ccf",false,{shape:"note"});if(s.pattern++%4===0)ring(s,480,92,14,155,"#7bdcff")}else{s.attack=.76;const x=rand(110,850);laser(s,x,80,x+rand(-80,80),H,.9,.46,"#ff203f",false);fan(s,480,92,s.player.x,s.player.y,3,.12,220,"#ff6a49")}}
  function banAttack(s){const fake=Math.random()<.43;if(Math.random()<.5)fan(s,480,92,s.player.x,s.player.y,3,.16,235,fake?"#8d5cff":"#ff244d",fake);else{const a=rand(0,6.283);for(let i=0;i<8;i++){const z=a+i*6.283/8;spawn(s,480,92,Math.cos(z)*205,Math.sin(z)*205,7,fake?"#8060ad":"#ff315c",fake,{curve:i%2?.3:-.3})}}if(s.pattern++%7===0)laser(s,rand(110,850),0,rand(110,850),H,.85,.4,"#ff244d",Math.random()<.45)}
  function laser(s,x1,y1,x2,y2,tele,active,color,fake){s.lasers.push({x1,y1,x2,y2,tele,active,color,fake,hit:false})}
  function startBan(s){const t=BAN[s.banIndex++%BAN.length],f=[0,1,2].filter(i=>i!==t.c);s.ban={truth:t,time:3.4,done:false,fake:f[Math.floor(Math.random()*f.length)]};s.banNext=999;s.feedback="BAN PROTOCOL · 不要相信綠色 SAFE";s.feedbackT=1.3}
  function banZones(){return[{x:175,y:485,r:74},{x:480,y:485,r:74},{x:785,y:485,r:74}]}
  function resolveBan(s){if(!s.ban)return;const z=banZones()[s.ban.truth.c],safe=d2(s.player.x,s.player.y,z.x,z.y)<z.r*z.r;s.ban.done=true;if(safe){s.boss.hp=clamp(s.boss.hp-150,0,MAX);s.resolve=clamp(s.resolve+25,0,100);s.feedback="TRUTH FILTER PASSED"}else{hit(s,true);s.feedback="BAN · FALSE SAFE ZONE"}s.feedbackT=1;s.bullets.length=0;s.lasers.length=0;s.ban=null;s.banNext=3.4}
  function bullets(s,dt){for(let i=s.bullets.length-1;i>=0;i--){const b=s.bullets[i];b.age+=dt;if(b.curve){const a=b.curve*dt,c=Math.cos(a),sn=Math.sin(a),vx=b.vx*c-b.vy*sn,vy=b.vx*sn+b.vy*c;b.vx=vx;b.vy=vy}if(b.wave)b.x+=Math.sin(b.age*b.wave*3)*22*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<-70||b.x>W+70||b.y<-80||b.y>H+80){s.bullets.splice(i,1);continue}const rr=b.r+R,dd=d2(b.x,b.y,s.player.x,s.player.y);if(!b.fake&&s.player.inv<=0&&dd<rr*rr){s.bullets.splice(i,1);hit(s,false);continue}if(!b.fake&&!b.g&&dd<(b.r+31)**2){b.g=true;s.graze++;s.resolve=clamp(s.resolve+2.2,0,100);s.score+=35}}}
  function lineDist(px,py,x1,y1,x2,y2){const dx=x2-x1,dy=y2-y1,l=dx*dx+dy*dy||1,t=clamp(((px-x1)*dx+(py-y1)*dy)/l,0,1),x=x1+t*dx,y=y1+t*dy;return Math.hypot(px-x,py-y)}function lasers(s,dt){for(let i=s.lasers.length-1;i>=0;i--){const l=s.lasers[i];if(l.tele>0){l.tele-=dt;continue}l.active-=dt;if(l.active<=0){s.lasers.splice(i,1);continue}if(!l.fake&&!l.hit&&s.player.inv<=0&&lineDist(s.player.x,s.player.y,l.x1,l.y1,l.x2,l.y2)<15){l.hit=true;hit(s,false)}}}
  function hit(s,forced){if(!forced&&s.player.inv>0)return;s.player.hp--;s.player.inv=1.05;s.resolve=clamp(s.resolve+8,0,100);navigator.vibrate?.(45)}
  function phaseCheck(s){if(s.phase===2&&s.boss.hp<=1500)enter(s,3,"ROOM DISTORTION");else if(s.phase===3&&s.boss.hp<=750)enter(s,4,"BAN MODE")}
  function dom(s){s.root.querySelector("[data-bossbar]").style.width=`${clamp(s.boss.hp/MAX*100,0,100)}%`;s.root.querySelector("[data-playerbar]").style.width=`${s.player.hp/PHP*100}%`;s.root.querySelector("[data-resolve]").style.width=`${s.resolve}%`;const names=["","MEMORY JUDGEMENT","TRIANGLE HELL","ROOM DISTORTION","BAN MODE"];s.root.querySelector("[data-phase-label]").textContent=names[s.phase];const b=s.root.querySelector("[data-special]");if(s.phase===1){b.disabled=s.qLock>0;b.textContent="確認答案"}else{b.disabled=s.resolve<100;b.textContent=s.resolve>=100?"CASE BREAK / 清彈":`CASE BREAK ${Math.floor(s.resolve)}%`}}
  function draw(s){const c=s.ctx;c.fillStyle="#07040b";c.fillRect(0,0,W,H);c.strokeStyle="rgba(174,71,255,.08)";for(let x=0;x<W;x+=48){c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke()}for(const l of s.lasers){c.strokeStyle=l.fake?"rgba(130,90,160,.22)":l.tele>0?"rgba(255,60,90,.35)":"#ff244d";c.lineWidth=l.tele>0?5:l.fake?9:18;c.beginPath();c.moveTo(l.x1,l.y1);c.lineTo(l.x2,l.y2);c.stroke()}for(const b of s.bullets){c.globalAlpha=b.fake?.25:1;c.fillStyle=b.color;if(b.shape==="desk")c.fillRect(b.x-14,b.y-9,28,18);else if(b.shape==="paper")c.fillRect(b.x-8,b.y-5,16,10);else if(b.shape==="note"){c.font="bold 20px sans-serif";c.fillText("♪",b.x-7,b.y+7)}else{c.beginPath();c.arc(b.x,b.y,b.r,0,6.283);c.fill()}}c.globalAlpha=1;c.fillStyle="#8df7ff";for(const a of s.shots)c.fillRect(a.x-2,a.y-8,4,14);drawBoss(c,s);drawZones(c,s);drawPlayer(c,s);drawHud(c,s)}
  function drawBoss(c,s){c.save();c.translate(480,92);c.strokeStyle=s.phase===4?"#ff3659":"#b66cff";c.fillStyle="rgba(35,8,45,.8)";c.lineWidth=5;c.beginPath();c.moveTo(0,-48);c.lineTo(58,43);c.lineTo(-58,43);c.closePath();c.fill();c.stroke();c.fillStyle="#fff";c.beginPath();c.ellipse(0,6,22,10,0,0,6.283);c.fill();c.fillStyle="#d51c4a";c.beginPath();c.arc(0,6,7,0,6.283);c.fill();c.restore()}
  function drawPlayer(c,s){const p=s.player;c.save();if(p.inv>0&&Math.floor(p.inv*14)%2===0)c.globalAlpha=.35;c.fillStyle="#eaffff";c.beginPath();c.moveTo(p.x,p.y-13);c.lineTo(p.x+9,p.y+10);c.lineTo(p.x,p.y+6);c.lineTo(p.x-9,p.y+10);c.closePath();c.fill();c.fillStyle="#ff315c";c.beginPath();c.arc(p.x,p.y,4,0,6.283);c.fill();c.restore()}
  function drawZones(c,s){if(s.phase===1&&s.q<QUESTIONS.length){const q=currentQ(s),z=answerZones(s);c.textAlign="center";z.forEach((a,i)=>{const inside=d2(s.player.x,s.player.y,a.x,a.y)<a.r*a.r;c.fillStyle=inside?"rgba(110,235,255,.18)":"rgba(90,45,120,.25)";c.strokeStyle=inside?"#8df7ff":"#b779e8";c.lineWidth=inside?4:2;c.beginPath();c.arc(a.x,a.y,a.r,0,6.283);c.fill();c.stroke();c.fillStyle="#fff";c.font="700 15px sans-serif";c.fillText(q.order[i],a.x,a.y+5)})}if(s.phase===4&&s.ban){const z=banZones(),t=s.ban.truth;c.textAlign="center";z.forEach((a,i)=>{c.fillStyle=i===s.ban.fake?"rgba(80,255,125,.13)":"rgba(130,60,160,.14)";c.strokeStyle=i===s.ban.fake?"#50ff7d":"#b96ae5";c.lineWidth=i===s.ban.fake?5:2;c.beginPath();c.arc(a.x,a.y,a.r,0,6.283);c.fill();c.stroke();c.fillStyle="#fff";c.fillText(t.labels[i],a.x,a.y+5)});c.fillStyle="#ff677f";c.fillText(`SYSTEM SAFE → ${t.labels[s.ban.fake]}（可能是假訊息）`,480,365);c.fillStyle="#fff0b0";c.fillText(t.note,480,392)}}
  function drawHud(c,s){c.textAlign="left";c.fillStyle="rgba(0,0,0,.62)";c.fillRect(18,18,275,68);c.fillStyle="#fff";c.font="800 13px monospace";c.fillText(`SCORE ${String(s.score).padStart(6,"0")}`,30,43);c.fillText(`GRAZE ${s.graze}`,30,65);if(s.phase===1&&s.q<QUESTIONS.length){c.textAlign="center";c.fillStyle="rgba(8,5,12,.85)";c.fillRect(150,126,660,72);c.fillStyle="#fff";c.font="800 19px sans-serif";c.fillText(QUESTIONS[s.q].q,480,158);c.fillStyle="#ceb0ff";c.font="12px sans-serif";c.fillText("答案順序每題重排，答案區也會移動",480,184)}if(s.feedbackT>0){c.textAlign="center";c.fillStyle="#fff";c.font="900 24px sans-serif";c.fillText(s.feedback,480,235)}}
  function win(s){if(s.finished)return;s.finished=true;s.feedback="PYRAMID COLLAPSE";s.feedbackT=2;setTimeout(()=>bridgeResult(s,true),800)}function lose(s){if(s.finished)return;s.finished=true;s.feedback="CONNECTION LOST";s.feedbackT=2;setTimeout(()=>bridgeResult(s,false),700)}
  function restore(s){modalCard.classList.remove("pyramid-boss-modal");body.innerHTML="";body.appendChild(s.legacy)}
  async function bridgeResult(s,won){bridge=true;const lostPhase=s.phase;stop();restore(s);const nf=()=>new Promise(r=>requestAnimationFrame(r));await nf();if(!won&&lostPhase===1){for(let i=0;i<5;i++){const qs=[...body.querySelectorAll("[data-q]")];qs.find(b=>!/第 32 張桌子/.test(b.textContent))?.click();await nf();if(!overlay.classList.contains("show"))break}}else{for(let g=0;g<70;g++){if(!overlay.classList.contains("show"))break;const qs=[...body.querySelectorAll("[data-q]")];if(qs.length){const correct=["第 32 張桌子","二樓窗戶","完成放學前沒完成的三件事"];qs.find(b=>correct.some(t=>b.textContent.includes(t)))?.click();await nf();continue}const lanes=[...body.querySelectorAll("#pyramidLanes [data-lane]")];if(lanes.length){const log=body.querySelector(".boss-log")?.textContent||"",m=log.match(/第\s*(\d+)\s*線/),danger=m?+m[1]-1:0;const b=won?lanes.find(x=>+x.dataset.lane!==danger):lanes.find(x=>+x.dataset.lane===danger);b?.click();await nf();continue}break}}setTimeout(()=>{bridge=false;schedule();window.GameAudio?.refreshBgmMode?.()},160)}
  function scan(){scheduled=false;if(session&&!document.contains(session.root))stop();if(!bridge&&!session&&legacyOpen())takeover()}function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(scan)}new MutationObserver(schedule).observe(body,{childList:true,subtree:true});new MutationObserver(schedule).observe(overlay,{attributes:true,attributeFilter:["class"]});schedule();
})();
